# https://www.python.org

# notas en una linea

'''
comentarios
en varias
lineas
'''

my_variable = "Mi variable"
print(my_variable)
my_variable = "Nuevo valor de mi variable"
print(my_variable)

my_int = 1
my_float = 1.5
my_bool = True
my_bool = False
my_string = "Hello, wolrd!"

print("Hello, World")
print(type(my_int))
print(type(my_float))
print(type(my_bool))
print(type(my_string))
print(type(my_variable))
